name: 'Github Topic Syncer'
description: 'Sync Github Topics from a Github Action'
branding:
  icon: refresh-cw
  color: gray-dark
runs:
  using: node16
  main: "dist/index.js"
inputs:
  topics:
    description: 'Space-separated topics to sync to Github'
    required: true
  token:
    description: 'Github token'
    required: true

